### ISSUE TITLE
[Feature]: Whether or not you will consider docker images for arm architecture

### ISSUE THREAD

**Issue by menxin123** [LiteLDev/levilamina-docker-server#10]
### Is your feature request related to a problem? Please describe.

Hopefully, subsequent mirrors will directly support arm or aarch64 architecture.

### Describe the solution you'd like

Compile an image that supports arm or aarch64, and execute x86 programs through the qemu emulation architecture.

**Comment by ShrBox** [comment]
Bedrock Dedicated Server only supports x86_64
Simulate BDS by using QEMU is low effiency
